### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by TheDoctorsLife** [LordLambda/Warden#2]
I get this error when executing pom.xml compile http://ci.bytelab.vps.thedoctorslife.com/job/Warden/4/console

**Comment by TheDoctorsLife** [comment]
http://ci.bytelab.vps.thedoctorslife.com/job/Warden/5/console should give u more infos

**Comment by LordLambda** [comment]
Looks like you have to force update as it isn't grabbing the protocollib dependency.

**Comment by LordLambda** [comment]
Let me know how that goes.

**Comment by LordLambda** [comment]
Also make sure your running mvn package.

**Comment by TheDoctorsLife** [comment]
Ahh, It works now http://ci.bytelab.vps.thedoctorslife.com/job/Warden/25/
