### ISSUE TITLE
Error in /src/main/java/io/ll/warden/storage/SQLite.java

### ISSUE THREAD

**Issue by TheDoctorsLife** [LordLambda/Warden#4]
http://ci.blastcraft.org:8080/view/All/job/Warden/2/console
ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/workspace/Warden/src/main/java/io/ll/warden/storage/SQLite.java:[53,47] cannot find symbol
symbol  : method toPath()
location: class java.io.File
[INFO] 1 error

**Comment by LordLambda** [comment]
Our entire SQL system has already been re-written waiting for @FerusGrim to push later this weekend.
