### ISSUE TITLE
Warden Build server

### ISSUE THREAD

**Issue by TheDoctorsLife** [LordLambda/Warden#6]
http://ci.blastcraft.org:8080/view/Sponge%20pluigins/job/Warden/ (Yes I will reverse proxy it soon)

**Comment by LordLambda** [comment]
What's the issue here?

**Comment by Favorlock** [comment]
Not an issue from what I can tell @LordLambda. I think he is just trying to inform us he has a build server up for Warden.

**Comment by LordLambda** [comment]
Alright then. Thanks @Favorlock. So I guess this brings up the question do we want this as an official build server or do we want our own?

**Comment by Favorlock** [comment]
I guess it really depends if @TheDoctorsLife can ensure that the build server will be reliable (e.g. little downtime, be available during project lifetime, etc). Safest option would be to host our own build server, but at this point in time I don't see it being a necessity to host our own.

**Comment by TheDoctorsLife** [comment]
I can ensure it's uptime, I had some early on issue because I was building with java 6 instead of java 7.

**Comment by LordLambda** [comment]
Alright. We'll wait on @FerusGrim to voice his input. For now though seems like for now we can set this as a build server.

**Comment by FerusGrim** [comment]
My input is that we shouldn't trust @TheDoctorsLife with this Build Server. I've got my own already, if we need it: https://ci.ferusgrim.me
